# Generated by Django 4.2.17 on 2024-12-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000),
            preserve_default=False,
        ),
    ]
